import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // The manifest at public/manifest.json is regenerated by `npm run rebuild`
  // and read by server components.
  experimental: {
    typedRoutes: false,
  },
};

export default nextConfig;
